import "/styles/globals.scss";
import "/styles/three.scss";
import { Inter } from "next/font/google";
import { EmotionCacheProvider } from "@/components/emotion-cache-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmotionCacheProvider>{children}</EmotionCacheProvider>
      </body>
    </html>
  );
}
